### PR TITLE
Test: Update runtime to v19.08beta

### PR DESCRIPTION
**Pull request by LeandroStanger**
https://github.com/flathub/net.minetest.Minetest/issues/6

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build net.minetest.Minetest

**Comment by LeandroStanger** [comment]
bot, build net.minetest.Minetest

**Comment by LeandroStanger** [comment]
bot, build net.minetest.Minetest

**Comment by LeandroStanger** [comment]
bot, build net.minetest.Minetest

**Comment by barthalion** [comment]
What does it have to do with #6?

**Pull request closed without merging**
