### PR TITLE
Bump the runtime to 21.08

### PR DESCRIPTION
**Pull request by farribeiro**
Update the runtime to latest version, the v21.08

### CODE REVIEW

**Comment by farribeiro** [comment]
btw... logged output build

**Comment by Calinou** [comment]
Upstream is now requiring a custom build of Irrlicht called IrrlichtMt: https://github.com/minetest/minetest

This may be the reason of the build failures.

**Comment by farribeiro** [comment]
Need a no-autogen module and dest argument

**Comment by farribeiro** [comment]
Abandonned

**Pull request closed without merging**
