### PR TITLE
Update Minetest to 5.8.0

### PR DESCRIPTION
**Pull request by farribeiro**
The minetest and irrlicht was updated... the game isn't needed.

Idk about update the luajit.

### CODE REVIEW

**Comment by Calinou** [comment]
The [5.7.0 Windows download](https://www.minetest.net/downloads/) still includes minetest_game out of the box, but I don't know if this applies to 5.8.0.

**Comment by farribeiro** [comment]
I read in the blog post what optional the game in 5.8.0

**Comment by farribeiro** [comment]
https://forum.minetest.net/viewtopic.php?p=429949#p429949

**Comment by farribeiro** [comment]
In release note https://github.com/minetest/minetest/releases/tag/5.8.0

**Comment by rubenwardy** [comment]
> For reference, the [5.7.0 Windows download](https://www.minetest.net/downloads/) still includes minetest_game out of the box, but I don't know if this applies to 5.8.0.

The first version without Minetest Game preinstalled is 5.8.0

**Review by rubenwardy — APPROVED** [review]
Tested, works as expected

**Review by Calinou — APPROVED** [review]

**Pull request merged**
