### PR TITLE
[WIP] bump to 5.9.0

### PR DESCRIPTION
**Pull request by farribeiro**
Preparing SDL2, opengl3 videodriver, wayland, change luajit and archive to git/tag for future release. Review and appreciation

PS: The newer minetest can build without this SDL2, i think because freedesktop platform has a small set of SDL2

### CODE REVIEW

**Comment by farribeiro** [comment]
failed in flathub validation, not in build

**Comment by farribeiro** [comment]
Idk if wants `USE_SDL2` and the `ENABLE_OPENGL3`  flag

**Comment by farribeiro** [comment]
bot, build

**Comment by farribeiro** [comment]
Could you use shared-modules luajit instead of the luajit module?

**Comment by Calinou** [comment]
> Could you use shared-modules luajit instead of the luajit module?

I think that should be fine, unless Minetest needs a more recent LuaJIT than what is packed in shared-modules.

**Comment by farribeiro** [comment]
> > Could you use shared-modules luajit instead of the luajit module?
> 
> I think that should be fine, unless Minetest needs a more recent LuaJIT than what is packaged in shared-modules. It's possible that LuaJIT wasn't in shared-modules when the Minetest Flatpak was first created.

@Calinou I made change to use luajit of flathub shared-modules

**Comment by farribeiro** [comment]
@Calinou  add some new args

**Comment by farribeiro** [comment]
Got it, the appstream linter has changed and now has an error in the 5.8.0 appstream

**Comment by farribeiro** [comment]
_mkhxjuuiy _

**Comment by farribeiro** [comment]
More improvements

**Comment by sfan5** [comment]
> luajit is in rolling release mode, but I heard someone say better to use luajit from openresty

Personally I would rather use the maintained upstream than a fork.

**Comment by farribeiro** [comment]
Closed for superseded the new pr

**Pull request closed without merging**
