### PR TITLE
Remove configs that aren't used in the build

### PR DESCRIPTION
**Pull request by farribeiro**
In my local build show the info what not be used on build theses configs, as it failed i will close just for knowledge

### CODE REVIEW

**Comment by farribeiro** [comment]
Reopened this PR because the error in not the build

**Comment by farribeiro** [comment]
https://github.com/minetest/minetest/issues/12597

**Comment by farribeiro** [comment]
Closed, temporary

**Comment by farribeiro** [comment]
Rebased the PR

**Comment by Calinou** [comment]
I've tested the build locally and it works.

**Pull request merged**
