### PR TITLE
LuaJIT: Use Git rather than last tagged release

### PR DESCRIPTION
**Pull request by farribeiro**
Its a draft PR to flathubbot build test

But i can turn a non draft PR

Linked issue #42

### CODE REVIEW

**Comment by farribeiro** [comment]
@Calinou 

Is good to replace tar.gz?

**Comment by Calinou** [comment]
> Is good to replace tar.gz?

I don't have a strong opinion on this.

**Comment by rollerozxa** [comment]
should be fine, most linux distros use a relatively recent development version of 2.1.0 straight from the master nowadays too

**Comment by rubenwardy** [comment]
LuaJIT no longer has releases, it's rolling release. So using a git version makes sense

**Comment by rubenwardy** [comment]
This should be renamed to something like "LuaJIT: Use git rather than last release"

**Review by Calinou — APPROVED** [review]
Tested locally, it works.

Thanks!

**Pull request merged**
